/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Chat;

import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.File;
import javax.swing.DefaultListModel;
import javax.swing.UIManager;

/**
 *
 * 
 */
public class ClientForm extends javax.swing.JFrame {

    public SocketClient client;
    public int port;
    public String serverAddr, username, password;
    public Thread clientThread;
    public DefaultListModel model;
    public File file;
    public String historyFile = "D:/History.xml";

    /**
     * Creates new form ClientForm
     */
    public ClientForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Chat Client "+userName.getText());
        model.addElement("All");
        jList1.setSelectedIndex(0);

        clientDisp.setEditable(false);

        this.addWindowListener(new WindowListener() {

            @Override
            public void windowOpened(WindowEvent e) {
            }

            @Override
            public void windowClosing(WindowEvent e) {
                try {
                    client.send(new Message("message", username, ".bye", "Server"));
                    clientThread.stop();
                } catch (Exception ex) {
                }
            }

            @Override
            public void windowClosed(WindowEvent e) {
            }

            @Override
            public void windowIconified(WindowEvent e) {
            }

            @Override
            public void windowDeiconified(WindowEvent e) {
            }

            @Override
            public void windowActivated(WindowEvent e) {
            }

            @Override
            public void windowDeactivated(WindowEvent e) {
            }
        });
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbl_connect = new javax.swing.JLabel();
        tbl_send = new javax.swing.JLabel();
        hostField = new javax.swing.JTextField();
        portField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        clientDisp = new javax.swing.JTextArea();
        inputClient = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        userName = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(651, 438));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_connect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_connectMouseClicked(evt);
            }
        });
        getContentPane().add(tbl_connect, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 50, 160, 60));

        tbl_send.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tbl_send.setToolTipText("");
        tbl_send.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_sendMouseClicked(evt);
            }
        });
        getContentPane().add(tbl_send, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 570, 190, 80));

        hostField.setBackground(new java.awt.Color(204, 255, 255));
        hostField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hostFieldActionPerformed(evt);
            }
        });
        getContentPane().add(hostField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 200, 30));

        portField.setBackground(new java.awt.Color(204, 255, 255));
        portField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portFieldActionPerformed(evt);
            }
        });
        getContentPane().add(portField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 112, 200, 30));

        jScrollPane1.setBorder(null);

        clientDisp.setBackground(new java.awt.Color(204, 255, 255));
        clientDisp.setColumns(20);
        clientDisp.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        clientDisp.setForeground(new java.awt.Color(204, 0, 51));
        clientDisp.setRows(5);
        jScrollPane1.setViewportView(clientDisp);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 720, 370));

        inputClient.setBackground(new java.awt.Color(204, 255, 255));
        inputClient.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inputClient.setBorder(null);
        inputClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputClientActionPerformed(evt);
            }
        });
        inputClient.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputClientKeyPressed(evt);
            }
        });
        getContentPane().add(inputClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 720, 70));

        jList1.setBackground(new java.awt.Color(204, 255, 255));
        jList1.setModel((model = new DefaultListModel()));
        jScrollPane2.setViewportView(jList1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 240, 190, 300));

        userName.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, 170, 30));

        jPasswordField1.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 170, 30));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/image.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 990, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hostFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hostFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hostFieldActionPerformed

    private void portFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_portFieldActionPerformed

    private void tbl_sendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_sendMouseClicked
        String msg = inputClient.getText();
        String nama = userName.getText();
        String target = jList1.getSelectedValue().toString();

        if (!msg.isEmpty() && !target.isEmpty()) {
            inputClient.setText("");
            client.send(new Message("message", username, msg, target));
        }
    }//GEN-LAST:event_tbl_sendMouseClicked

    private void tbl_connectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_connectMouseClicked
        serverAddr = hostField.getText();
        port = Integer.parseInt(portField.getText());
        if (!serverAddr.isEmpty() && !portField.getText().isEmpty()) {
            try {
                client = new SocketClient(this);
                clientThread = new Thread(client);
                clientThread.start();
                client.send(new Message("test", "testUser", "testContent", "Server"));
            } catch (Exception ex) {
                clientDisp.append("[Application to Me] : Server not found\n");
            }
        }
        //--
        username = userName.getText();
        password = jPasswordField1.getText();

        if (!username.isEmpty() && !password.isEmpty()) {
            client.send(new Message("signup", username, password, "Server"));
        }

    }//GEN-LAST:event_tbl_connectMouseClicked

    private void inputClientKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputClientKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            String msg = inputClient.getText();
            String nama = userName.getText();
            String target = jList1.getSelectedValue().toString();

            if (!msg.isEmpty() && !target.isEmpty()) {
                inputClient.setText("");
                client.send(new Message("message", username, msg, target));
            }
        }
    }//GEN-LAST:event_inputClientKeyPressed

    private void inputClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputClientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
            System.out.println("Look & Feel exception");
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextArea clientDisp;
    public javax.swing.JTextField hostField;
    public javax.swing.JTextField inputClient;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JList jList1;
    public javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextField portField;
    private javax.swing.JLabel tbl_connect;
    private javax.swing.JLabel tbl_send;
    public javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables
}
