/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Chat;

import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.UIManager;

/**
 *
 * 
 */
public class ServerForm extends javax.swing.JFrame {

    public SocketServer server;
    //public SocketClient client;
    public Thread serverThread;
    public String username;
    public DefaultListModel model;
    public String filePath = "D:/Data.xml";
    public JFileChooser fileChooser;
    public ClientForm cf;

    /**
     * Creates new form ServerForm
     */
    public ServerForm() {
        initComponents();
        display.setEditable(false);
        this.setLocationRelativeTo(null);

    }

    public boolean isWin32() {
        return System.getProperty("os.name").startsWith("Windows");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_connect = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        display = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_connect.setBackground(new java.awt.Color(255, 102, 204));
        btn_connect.setForeground(new java.awt.Color(204, 255, 204));
        btn_connect.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_connect.setToolTipText("");
        btn_connect.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_connect.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_connect.setVerifyInputWhenFocusTarget(false);
        btn_connect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_connectMouseClicked(evt);
            }
        });
        getContentPane().add(btn_connect, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 90, 160, 50));

        jScrollPane1.setBorder(null);
        jScrollPane1.setOpaque(false);

        display.setBackground(new java.awt.Color(204, 255, 255));
        display.setColumns(20);
        display.setFont(new java.awt.Font(".VnArial", 0, 18)); // NOI18N
        display.setRows(5);
        display.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.white));
        display.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        display.setName(""); // NOI18N
        jScrollPane1.setViewportView(display);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 820, 470));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aurora.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 1040, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_connectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_connectMouseClicked
        server = new SocketServer(this); 
    }//GEN-LAST:event_btn_connectMouseClicked

    public void RetryStart(int port) {
        if (server != null) {
            server.stop();
        }
        server = new SocketServer(this, port);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
            System.out.println("Look & Feel Exception");
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_connect;
    public javax.swing.JTextArea display;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
